### ISSUE TITLE
As a standardbounties user, id like to be able to fulfill after the expiration date.

### ISSUE THREAD

**Issue by owocki** [Bounties-Network/StandardBounties#25]
https://beta.bounties.network/bounty/v1/29
https://github.com/MarketProject/Dapp/issues/30

# Expected behaviour

I should be able to submit work after the expiration date. 
or
As a bounty submitter, I should be able to configure my bounty such that the expiration date is a soft target.

# Current behaviour

Users submission `throws()` when submission happens after expiration date

http://bits.owocki.com/1I3P2W0r1x0U/Screen%20Shot%202018-02-12%20at%2010.04.52%20AM.png

**Comment by vs77bb** [comment]
@mbeylin Got a bump on this from a community member looking for this functionality. Any word on where it is on the roadmap?

**Comment by mbeylin** [comment]
Deadlines are being removed in version 2.0 of StandardBounties so this won't be an issue when we eventually complete and deploy that. 

However in the meantime, 3 solutions exist:
- bounty issuers pick a deadline, and can extend it if they desire (this functionality exists in the currently live standard bounties contract)
- bounty issuers pick a deadline that's really far in advance knowing they don't care about deadline
- the deadline you enter on gitcoin is stored off-chain (in the JSON object that's on IPFS), and the on-chain deadline is just max_int or something like that to ensure it never really expires

**Comment by PixelantDesign** [comment]
As a funder, I've been posting my tasks with a 1 week expiration. Can I got back and update the time frame in the ticket?

**Comment by PixelantDesign** [comment]
I like this solution: the deadline you enter on gitcoin is stored off-chain (in the JSON object that's on IPFS), and the on-chain deadline is just max_int or something like that to ensure it never really expires

**Comment by vs77bb** [comment]
@owocki Very nice!

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/566

deployed this today!
