### ISSUE TITLE
Milestones are not defined

### ISSUE THREAD

**Issue by martinklepsch** [Bounties-Network/StandardBounties#30]
The README mentions milestones in a couple of places but the contracts as well as the other descriptions don't really seem to have a concept like milestones. Could you explain and/or update the documentation what role milestones play in the StandardBounties workflow?

**Comment by mbeylin** [comment]
Will open a PR to fix this now. Thanks for bringing this to our attention. 

For your dev efforts, the /documentation/ repo will have the best record of expected performance.
