### ISSUE TITLE
bug: mainnet bounty shows wrong text when logged on rinkerby

### ISSUE THREAD

**Issue by thelostone-mc** [Bounties-Network/StandardBounties#44]
#### Description 

Login into the test net (rinkerby) via metamask and open a bounty funded on the mainnet like
https://beta.bounties.network/bounty/v1/486

You get the following message!

<img width="1440" alt="screen shot 2018-05-24 at 5 26 28 pm" src="https://user-images.githubusercontent.com/5358146/40484027-bad21dbc-5f77-11e8-8836-3e492f772fca.png">

#### Fix

 Update the content to use the current active network rather than hardcoding the message

**Comment by villanuevawill** [comment]
@thelostone-mc - 485 and 487 show up.  This is a pretty extreme edge case where 486 does not exist on the rinkeby testnet.  Most ids will exist from the mainnet that exist on rinkeby. We should def. update this, but I think there are only 3 ids that don't exist in rinkeby that exist in mainnet.

**Comment by thelostone-mc** [comment]
Ah cool @villanuevawill 
Closing this as I opened it in the wrong repo 😅
