### ISSUE TITLE
Completing a bounty with a wallet with no wei in it.

### ISSUE THREAD

**Issue by ChrisCates** [Bounties-Network/StandardBounties#49]
This issue came up here: https://github.com/gitcoinco/web/issues/2243

I'm curious if you guys have any suggestions on the best method of implementation.
I think this is an interesting topic to discuss.

Gitcoin.co does have a faucet for people to submit bounties. However, I think that we should consider a more effective method where someone could potentially sign a transaction for the fulfiller (such as the issuer).

This way, the issuer can sign the transaction and then send the ETH to the person who completed the bounty.

Ultimately the way I see this working is:

1. The fulfiller can sign the transaction claiming they have completed the bounty. **(Which would be the original functionality already there)**

2. The issuer can sign the transaction and specify who to send the bounty to. **(Which would be the new functionality)**

**_Let me know if you guys have any feedback!_**

**Comment by ChrisCates** [comment]
After looking into this problem further.
This project came up: https://github.com/ahmb84/fuel-node-example

Perhaps this could be integrated into a StandardBounties Web Application on Rinkeby or Ropsten for demonstration purposes?

**Comment by mbeylin** [comment]
@ChrisCates So in the new version of StandardBounties (on the development branch) you'll see that new bounties and new submissions can be created by anyone on someone else's behalf. IMO this achieves the same solution you were describing, where:
- user submits work, signs a message saying theyre submitting the work
- our server receives the signed message, submits that work on their behalf
- when the submission gets accepted, the original submitter gets paid

While unfortunately this functionality doesnt exist in our current contracts, seeing as we've now frozen the STDB2.0 code and are awaiting a code audit, I'm not sure it makes sense to build a solution for the existing contract.

**Comment by ChrisCates** [comment]
@mbeylin, makes perfect sense!
Thanks for making these clarifications.
