### ISSUE TITLE
Verify Contract of Deployments displayed in Readme on Etherscan

### ISSUE THREAD

**Issue by edsonayllon** [Bounties-Network/StandardBounties#80]
For the addresses displayed in the Readme, the contract display in Etherscan is marked as unverified.

https://etherscan.io/address/0xa7135d0a62939501b5304a04bf00d1a9a22f6623#code

**Comment by mbeylin** [comment]
Hey Edson, I've gone ahead and verified it. Thank you for bringing this to our attention! 👍
